name: Release

on:
  push:
    branches:
      - '*'

  workflow_call:
  workflow_dispatch:

jobs:
  build-device:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      KEY_AVB: ${{ secrets.KEY_AVB }}
      KEY_OTA: ${{ secrets.KEY_OTA }}
      CERT_OTA: ${{ secrets.CERT_OTA }}
      PASSPHRASE_AVB: ${{ secrets.PASSPHRASE_AVB }}
      PASSPHRASE_OTA: ${{ secrets.PASSPHRASE_OTA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: load keys
        run: |
          echo "$KEY_AVB" | base64 --decode > keys/avb.key
          echo "$KEY_OTA" | base64 --decode > keys/ota.key
          echo "$CERT_OTA" | base64 --decode > keys/ota.crt
      - name: list keys
        run: ls -la keys/
      - name: show key hashes
        run: |
          sha256sum keys/avb.key
          sha256sum keys/ota.key
          sha256sum keys/ota.crt
      - name: Create OTA update
        run: |
          python3 main.py
      - name: Display files
        run: ls -la ota/

      - name: load release info from env var file
        id: load_release_info
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ota/release_info
      - name: show release info
        run: |
         echo "Device: $device"
         echo "Build ID: $build_id"
         echo "Android Version: $android_version"
         echo "OTA: $ota"
      - name: Create Release 
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.build_id }}
          name: ${{ env.build_id }}
          files: |
            ota/*.zip
            ota/*.zip.csig

      - name: upload update info
        uses: actions/upload-pages-artifact@v3
        with:
          path: ota/
          branch: gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-device
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


